language: go
go:
- 1.4.2
- 1.5
- tip


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get golang.org/x/tools/cmd/vet
- go get github.com/kisielk/errcheck


script:
- go test -v -race -timeout=90s github.com/alpe/messaging_spike/...
- go vet github.com/alpe/messaging_spike/...
- errcheck github.com/alpe/messaging_spike/...
- go test -bench '.*' -run none github.com/alpe/messaging_spike/...

env:
- GOMAXPROCS=4

sudo: false